[workspace]
resolver = "2"

members = [
    # federal etl
    "fh-scraper",
    "fh-translator",

    # queens park etl
    "qp-scraper",
    "qp-translator",
    
    # analysis app
    "backend",
    "frontend",
    
    # internal
    "common",
    "db"
]
