[profile.release]
lto = true

[profile.release.package.frontend]
opt-level = "s"

[workspace]
resolver = "2"

members = [
    # app
    "backend",
    "frontend",
    
    # internal
    "common",
    "db"
]
