use diesel::prelude::*;
use diesel::r2d2::{ConnectionManager, Pool};
use dotenvy::dotenv;
use std::env;
use time::PrimitiveDateTime;
use time::macros::{date, time};
use common::models::*;

pub fn get_connection_pool() -> Pool<ConnectionManager<MysqlConnection>> {
    dotenv().ok();

    let database_url = format!("{}{}",
        env::var("DATABASE_URL").expect("DATABASE_URL must be set"),
        env::var("DATA_SOURCE").expect("DATA_SOURCE must be set")
    );
    let manager = ConnectionManager::<MysqlConnection>::new(database_url);
    
    Pool::builder()
        .max_size(50) // todo find a sane default number here
        .min_idle(Some(10)) // todo same
        .build(manager)
        .expect("Could not build connection pool")
}

pub fn get_speakers(_connection: &mut MysqlConnection) -> Vec<SpeakerResponse> {
    vec![
        SpeakerResponse {id:1,first_name:"Ziad".to_string(),last_name:"Aboultaif".to_string()},
        SpeakerResponse {id:2,first_name:"Scott".to_string(),last_name:"Aitchison".to_string()},
        SpeakerResponse {id:3,first_name:"Dan".to_string(),last_name:"Albas".to_string()},
        SpeakerResponse {id:4,first_name:"John".to_string(),last_name:"Aldag".to_string()},
        SpeakerResponse {id:5,first_name:"Omar".to_string(),last_name:"Alghabra".to_string()},
        SpeakerResponse {id:6,first_name:"Shafqat".to_string(),last_name:"Ali".to_string()},
        SpeakerResponse {id:7,first_name:"Dean".to_string(),last_name:"Allison".to_string()},
        SpeakerResponse {id:8,first_name:"Anita".to_string(),last_name:"Anand".to_string()},
        SpeakerResponse {id:9,first_name:"Gary".to_string(),last_name:"Anandasangaree".to_string()},
        SpeakerResponse {id:10,first_name:"Charlie".to_string(),last_name:"Angus".to_string()},
        SpeakerResponse {id:11,first_name:"Mel".to_string(),last_name:"Arnold".to_string()},
        SpeakerResponse {id:12,first_name:"René".to_string(),last_name:"Arseneault".to_string()},
        SpeakerResponse {id:13,first_name:"Chandra".to_string(),last_name:"Arya".to_string()},
        SpeakerResponse {id:14,first_name:"Niki".to_string(),last_name:"Ashton".to_string()},
        SpeakerResponse {id:15,first_name:"Jenica".to_string(),last_name:"Atwin".to_string()},
        SpeakerResponse {id:16,first_name:"Taylor".to_string(),last_name:"Bachrach".to_string()},
        SpeakerResponse {id:17,first_name:"Vance".to_string(),last_name:"Badawey".to_string()},
        SpeakerResponse {id:18,first_name:"Parm".to_string(),last_name:"Bains".to_string()},
        SpeakerResponse {id:19,first_name:"Yvan".to_string(),last_name:"Baker".to_string()},
        SpeakerResponse {id:20,first_name:"Tony".to_string(),last_name:"Baldinelli".to_string()},
        SpeakerResponse {id:21,first_name:"John".to_string(),last_name:"Barlow".to_string()},
        SpeakerResponse {id:22,first_name:"Michael".to_string(),last_name:"Barrett".to_string()},
        SpeakerResponse {id:23,first_name:"Lisa Marie".to_string(),last_name:"Barron".to_string()},
        SpeakerResponse {id:24,first_name:"Xavier".to_string(),last_name:"Barsalou-Duval".to_string()},
        SpeakerResponse {id:25,first_name:"Jaime".to_string(),last_name:"Battiste".to_string()},
        SpeakerResponse {id:26,first_name:"Mario".to_string(),last_name:"Beaulieu".to_string()},
        SpeakerResponse {id:27,first_name:"Terry".to_string(),last_name:"Beech".to_string()},
        SpeakerResponse {id:28,first_name:"Rachel".to_string(),last_name:"Bendayan".to_string()},
        SpeakerResponse {id:29,first_name:"Carolyn".to_string(),last_name:"Bennett".to_string()},
        SpeakerResponse {id:30,first_name:"Bob".to_string(),last_name:"Benzen".to_string()},
        SpeakerResponse {id:31,first_name:"Candice".to_string(),last_name:"Bergen".to_string()},
        SpeakerResponse {id:32,first_name:"Stéphane".to_string(),last_name:"Bergeron".to_string()},
        SpeakerResponse {id:33,first_name:"Luc".to_string(),last_name:"Berthold".to_string()},
        SpeakerResponse {id:34,first_name:"Sylvie".to_string(),last_name:"Bérubé".to_string()},
        SpeakerResponse {id:35,first_name:"James".to_string(),last_name:"Bezan".to_string()},
        SpeakerResponse {id:36,first_name:"Marie-Claude".to_string(),last_name:"Bibeau".to_string()},
        SpeakerResponse {id:37,first_name:"Chris".to_string(),last_name:"Bittle".to_string()},
        SpeakerResponse {id:38,first_name:"Daniel".to_string(),last_name:"Blaikie".to_string()},
        SpeakerResponse {id:39,first_name:"Bill".to_string(),last_name:"Blair".to_string()},
        SpeakerResponse {id:40,first_name:"Yves-François".to_string(),last_name:"Blanchet".to_string()},
        SpeakerResponse {id:41,first_name:"Maxime".to_string(),last_name:"Blanchette-Joncas".to_string()},
        SpeakerResponse {id:42,first_name:"Rachel".to_string(),last_name:"Blaney".to_string()},
        SpeakerResponse {id:43,first_name:"Kelly".to_string(),last_name:"Block".to_string()},
        SpeakerResponse {id:44,first_name:"Kody".to_string(),last_name:"Blois".to_string()},
        SpeakerResponse {id:45,first_name:"Randy".to_string(),last_name:"Boissonnault".to_string()},
        SpeakerResponse {id:46,first_name:"Alexandre".to_string(),last_name:"Boulerice".to_string()},
        SpeakerResponse {id:47,first_name:"Valerie".to_string(),last_name:"Bradford".to_string()},
        SpeakerResponse {id:48,first_name:"Richard".to_string(),last_name:"Bragdon".to_string()},
        SpeakerResponse {id:49,first_name:"John".to_string(),last_name:"Brassard".to_string()},
        SpeakerResponse {id:50,first_name:"Élisabeth".to_string(),last_name:"Brière".to_string()},
        SpeakerResponse {id:51,first_name:"Larry".to_string(),last_name:"Brock".to_string()},
        SpeakerResponse {id:52,first_name:"Alexis".to_string(),last_name:"Brunelle-Duceppe".to_string()},
        SpeakerResponse {id:53,first_name:"Blaine".to_string(),last_name:"Calkins".to_string()},
        SpeakerResponse {id:54,first_name:"Richard".to_string(),last_name:"Cannings".to_string()},
        SpeakerResponse {id:55,first_name:"Frank".to_string(),last_name:"Caputo".to_string()},
        SpeakerResponse {id:56,first_name:"Ben".to_string(),last_name:"Carr".to_string()},
        SpeakerResponse {id:57,first_name:"Jim".to_string(),last_name:"Carr".to_string()},
        SpeakerResponse {id:58,first_name:"Colin".to_string(),last_name:"Carrie".to_string()},
        SpeakerResponse {id:59,first_name:"Sean".to_string(),last_name:"Casey".to_string()},
        SpeakerResponse {id:60,first_name:"Louise".to_string(),last_name:"Chabot".to_string()},
        SpeakerResponse {id:61,first_name:"Bardish".to_string(),last_name:"Chagger".to_string()},
        SpeakerResponse {id:62,first_name:"George".to_string(),last_name:"Chahal".to_string()},
        SpeakerResponse {id:63,first_name:"Adam".to_string(),last_name:"Chambers".to_string()},
        SpeakerResponse {id:64,first_name:"François-Philippe".to_string(),last_name:"Champagne".to_string()},
        SpeakerResponse {id:65,first_name:"Martin".to_string(),last_name:"Champoux".to_string()},
        SpeakerResponse {id:66,first_name:"Sophie".to_string(),last_name:"Chatel".to_string()},
        SpeakerResponse {id:67,first_name:"Shaun".to_string(),last_name:"Chen".to_string()},
        SpeakerResponse {id:68,first_name:"Paul".to_string(),last_name:"Chiang".to_string()},
        SpeakerResponse {id:69,first_name:"Michael".to_string(),last_name:"Chong".to_string()},
        SpeakerResponse {id:70,first_name:"Chad".to_string(),last_name:"Collins".to_string()},
        SpeakerResponse {id:71,first_name:"Laurel".to_string(),last_name:"Collins".to_string()},
        SpeakerResponse {id:72,first_name:"Michael".to_string(),last_name:"Cooper".to_string()},
        SpeakerResponse {id:73,first_name:"Serge".to_string(),last_name:"Cormier".to_string()},
        SpeakerResponse {id:74,first_name:"Michael".to_string(),last_name:"Coteau".to_string()},
        SpeakerResponse {id:75,first_name:"Chris".to_string(),last_name:"d'Entremont".to_string()},
        SpeakerResponse {id:76,first_name:"Julie".to_string(),last_name:"Dabrusin".to_string()},
        SpeakerResponse {id:77,first_name:"Marc".to_string(),last_name:"Dalton".to_string()},
        SpeakerResponse {id:78,first_name:"Pam".to_string(),last_name:"Damoff".to_string()},
        SpeakerResponse {id:79,first_name:"Leila".to_string(),last_name:"Dance".to_string()},
        SpeakerResponse {id:80,first_name:"Raquel".to_string(),last_name:"Dancho".to_string()},
        SpeakerResponse {id:81,first_name:"Scot".to_string(),last_name:"Davidson".to_string()},
        SpeakerResponse {id:82,first_name:"Don".to_string(),last_name:"Davies".to_string()},
        SpeakerResponse {id:83,first_name:"Claude".to_string(),last_name:"DeBellefeuille".to_string()},
        SpeakerResponse {id:84,first_name:"Gérard".to_string(),last_name:"Deltell".to_string()},
        SpeakerResponse {id:85,first_name:"Caroline".to_string(),last_name:"Desbiens".to_string()},
        SpeakerResponse {id:86,first_name:"Luc".to_string(),last_name:"Desilets".to_string()},
        SpeakerResponse {id:87,first_name:"Blake".to_string(),last_name:"Desjarlais".to_string()},
        SpeakerResponse {id:88,first_name:"Sukh".to_string(),last_name:"Dhaliwal".to_string()},
        SpeakerResponse {id:89,first_name:"Anju".to_string(),last_name:"Dhillon".to_string()},
        SpeakerResponse {id:90,first_name:"Lena".to_string(),last_name:"Diab".to_string()},
        SpeakerResponse {id:91,first_name:"Todd".to_string(),last_name:"Doherty".to_string()},
        SpeakerResponse {id:92,first_name:"Han".to_string(),last_name:"Dong".to_string()},
        SpeakerResponse {id:93,first_name:"Terry".to_string(),last_name:"Dowdall".to_string()},
        SpeakerResponse {id:94,first_name:"Earl".to_string(),last_name:"Dreeshen".to_string()},
        SpeakerResponse {id:95,first_name:"Francis".to_string(),last_name:"Drouin".to_string()},
        SpeakerResponse {id:96,first_name:"Emmanuel".to_string(),last_name:"Dubourg".to_string()},
        SpeakerResponse {id:97,first_name:"Jean-Yves".to_string(),last_name:"Duclos".to_string()},
        SpeakerResponse {id:98,first_name:"Terry".to_string(),last_name:"Duguid".to_string()},
        SpeakerResponse {id:99,first_name:"Eric".to_string(),last_name:"Duncan".to_string()},
        SpeakerResponse {id:100,first_name:"Kirsty".to_string(),last_name:"Duncan".to_string()},
        SpeakerResponse {id:101,first_name:"Julie".to_string(),last_name:"Dzerowicz".to_string()},
        SpeakerResponse {id:102,first_name:"Ali".to_string(),last_name:"Ehsassi".to_string()},
        SpeakerResponse {id:103,first_name:"Fayçal".to_string(),last_name:"El-Khoury".to_string()},
        SpeakerResponse {id:104,first_name:"Stephen".to_string(),last_name:"Ellis".to_string()},
        SpeakerResponse {id:105,first_name:"Dave".to_string(),last_name:"Epp".to_string()},
        SpeakerResponse {id:106,first_name:"Nathaniel".to_string(),last_name:"Erskine-Smith".to_string()},
        SpeakerResponse {id:107,first_name:"Rosemarie".to_string(),last_name:"Falk".to_string()},
        SpeakerResponse {id:108,first_name:"Ted".to_string(),last_name:"Falk".to_string()},
        SpeakerResponse {id:109,first_name:"Ed".to_string(),last_name:"Fast".to_string()},
        SpeakerResponse {id:110,first_name:"Greg".to_string(),last_name:"Fergus".to_string()},
        SpeakerResponse {id:111,first_name:"Michelle".to_string(),last_name:"Ferreri".to_string()},
        SpeakerResponse {id:112,first_name:"Andy".to_string(),last_name:"Fillmore".to_string()},
        SpeakerResponse {id:113,first_name:"Kerry-Lynne".to_string(),last_name:"Findlay".to_string()},
        SpeakerResponse {id:114,first_name:"Darren".to_string(),last_name:"Fisher".to_string()},
        SpeakerResponse {id:115,first_name:"Peter".to_string(),last_name:"Fonseca".to_string()},
        SpeakerResponse {id:116,first_name:"Mona".to_string(),last_name:"Fortier".to_string()},
        SpeakerResponse {id:117,first_name:"Rhéal".to_string(),last_name:"Fortin".to_string()},
        SpeakerResponse {id:118,first_name:"Peter".to_string(),last_name:"Fragiskatos".to_string()},
        SpeakerResponse {id:119,first_name:"Sean".to_string(),last_name:"Fraser".to_string()},
        SpeakerResponse {id:120,first_name:"Chrystia".to_string(),last_name:"Freeland".to_string()},
        SpeakerResponse {id:121,first_name:"Hedy".to_string(),last_name:"Fry".to_string()},
        SpeakerResponse {id:122,first_name:"Iqwinder".to_string(),last_name:"Gaheer".to_string()},
        SpeakerResponse {id:123,first_name:"Anna".to_string(),last_name:"Gainey".to_string()},
        SpeakerResponse {id:124,first_name:"Cheryl".to_string(),last_name:"Gallant".to_string()},
        SpeakerResponse {id:125,first_name:"Marc".to_string(),last_name:"Garneau".to_string()},
        SpeakerResponse {id:126,first_name:"Jean-Denis".to_string(),last_name:"Garon".to_string()},
        SpeakerResponse {id:127,first_name:"Randall".to_string(),last_name:"Garrison".to_string()},
        SpeakerResponse {id:128,first_name:"Marie-Hélène".to_string(),last_name:"Gaudreau".to_string()},
        SpeakerResponse {id:129,first_name:"Leah".to_string(),last_name:"Gazan".to_string()},
        SpeakerResponse {id:130,first_name:"Bernard".to_string(),last_name:"Généreux".to_string()},
        SpeakerResponse {id:131,first_name:"Garnett".to_string(),last_name:"Genuis".to_string()},
        SpeakerResponse {id:132,first_name:"Mark".to_string(),last_name:"Gerretsen".to_string()},
        SpeakerResponse {id:133,first_name:"Marilène".to_string(),last_name:"Gill".to_string()},
        SpeakerResponse {id:134,first_name:"Marilyn".to_string(),last_name:"Gladu".to_string()},
        SpeakerResponse {id:135,first_name:"Joël".to_string(),last_name:"Godin".to_string()},
        SpeakerResponse {id:136,first_name:"Laila".to_string(),last_name:"Goodridge".to_string()},
        SpeakerResponse {id:137,first_name:"Karina".to_string(),last_name:"Gould".to_string()},
        SpeakerResponse {id:138,first_name:"Jacques".to_string(),last_name:"Gourde".to_string()},
        SpeakerResponse {id:139,first_name:"Tracy".to_string(),last_name:"Gray".to_string()},
        SpeakerResponse {id:140,first_name:"Matthew".to_string(),last_name:"Green".to_string()},
        SpeakerResponse {id:141,first_name:"Steven".to_string(),last_name:"Guilbeault".to_string()},
        SpeakerResponse {id:142,first_name:"Patty".to_string(),last_name:"Hajdu".to_string()},
        SpeakerResponse {id:143,first_name:"Jasraj".to_string(),last_name:"Hallan".to_string()},
        SpeakerResponse {id:144,first_name:"Brendan".to_string(),last_name:"Hanley".to_string()},
        SpeakerResponse {id:145,first_name:"Ken".to_string(),last_name:"Hardie".to_string()},
        SpeakerResponse {id:146,first_name:"Lisa".to_string(),last_name:"Hepfner".to_string()},
        SpeakerResponse {id:147,first_name:"Randy".to_string(),last_name:"Hoback".to_string()},
        SpeakerResponse {id:148,first_name:"Mark".to_string(),last_name:"Holland".to_string()},
        SpeakerResponse {id:149,first_name:"Anthony".to_string(),last_name:"Housefather".to_string()},
        SpeakerResponse {id:150,first_name:"Carol".to_string(),last_name:"Hughes".to_string()},
        SpeakerResponse {id:151,first_name:"Ahmed".to_string(),last_name:"Hussen".to_string()},
        SpeakerResponse {id:152,first_name:"Gudie".to_string(),last_name:"Hutchings".to_string()},
        SpeakerResponse {id:153,first_name:"Angelo".to_string(),last_name:"Iacono".to_string()},
        SpeakerResponse {id:154,first_name:"Lori".to_string(),last_name:"Idlout".to_string()},
        SpeakerResponse {id:155,first_name:"Marci".to_string(),last_name:"Ien".to_string()},
        SpeakerResponse {id:156,first_name:"Helena".to_string(),last_name:"Jaczek".to_string()},
        SpeakerResponse {id:157,first_name:"Tamara".to_string(),last_name:"Jansen".to_string()},
        SpeakerResponse {id:158,first_name:"Matt".to_string(),last_name:"Jeneroux".to_string()},
        SpeakerResponse {id:159,first_name:"Jamil".to_string(),last_name:"Jivani".to_string()},
        SpeakerResponse {id:160,first_name:"Gord".to_string(),last_name:"Johns".to_string()},
        SpeakerResponse {id:161,first_name:"Mélanie".to_string(),last_name:"Joly".to_string()},
        SpeakerResponse {id:162,first_name:"Yvonne".to_string(),last_name:"Jones".to_string()},
        SpeakerResponse {id:163,first_name:"Majid".to_string(),last_name:"Jowhari".to_string()},
        SpeakerResponse {id:164,first_name:"Peter".to_string(),last_name:"Julian".to_string()},
        SpeakerResponse {id:165,first_name:"Arielle".to_string(),last_name:"Kayabaga".to_string()},
        SpeakerResponse {id:166,first_name:"Mike".to_string(),last_name:"Kelloway".to_string()},
        SpeakerResponse {id:167,first_name:"Pat".to_string(),last_name:"Kelly".to_string()},
        SpeakerResponse {id:168,first_name:"Iqra".to_string(),last_name:"Khalid".to_string()},
        SpeakerResponse {id:169,first_name:"Arpan".to_string(),last_name:"Khanna".to_string()},
        SpeakerResponse {id:170,first_name:"Kamal".to_string(),last_name:"Khera".to_string()},
        SpeakerResponse {id:171,first_name:"Robert".to_string(),last_name:"Kitchen".to_string()},
        SpeakerResponse {id:172,first_name:"Tom".to_string(),last_name:"Kmiec".to_string()},
        SpeakerResponse {id:173,first_name:"Annie".to_string(),last_name:"Koutrakis".to_string()},
        SpeakerResponse {id:174,first_name:"Michael".to_string(),last_name:"Kram".to_string()},
        SpeakerResponse {id:175,first_name:"Shelby".to_string(),last_name:"Kramp-Neuman".to_string()},
        SpeakerResponse {id:176,first_name:"Damien".to_string(),last_name:"Kurek".to_string()},
        SpeakerResponse {id:177,first_name:"Stephanie".to_string(),last_name:"Kusie".to_string()},
        SpeakerResponse {id:178,first_name:"Irek".to_string(),last_name:"Kusmierczyk".to_string()},
        SpeakerResponse {id:179,first_name:"Jenny".to_string(),last_name:"Kwan".to_string()},
        SpeakerResponse {id:180,first_name:"Mike".to_string(),last_name:"Lake".to_string()},
        SpeakerResponse {id:181,first_name:"Marie-France".to_string(),last_name:"Lalonde".to_string()},
        SpeakerResponse {id:182,first_name:"Emmanuella".to_string(),last_name:"Lambropoulos".to_string()},
        SpeakerResponse {id:183,first_name:"David".to_string(),last_name:"Lametti".to_string()},
        SpeakerResponse {id:184,first_name:"Kevin".to_string(),last_name:"Lamoureux".to_string()},
        SpeakerResponse {id:185,first_name:"Melissa".to_string(),last_name:"Lantsman".to_string()},
        SpeakerResponse {id:186,first_name:"Viviane".to_string(),last_name:"Lapointe".to_string()},
        SpeakerResponse {id:187,first_name:"Andréanne".to_string(),last_name:"Larouche".to_string()},
        SpeakerResponse {id:188,first_name:"Patricia".to_string(),last_name:"Lattanzio".to_string()},
        SpeakerResponse {id:189,first_name:"Stéphane".to_string(),last_name:"Lauzon".to_string()},
        SpeakerResponse {id:190,first_name:"Philip".to_string(),last_name:"Lawrence".to_string()},
        SpeakerResponse {id:191,first_name:"Dominic".to_string(),last_name:"LeBlanc".to_string()},
        SpeakerResponse {id:192,first_name:"Diane".to_string(),last_name:"Lebouthillier".to_string()},
        SpeakerResponse {id:193,first_name:"Richard".to_string(),last_name:"Lehoux".to_string()},
        SpeakerResponse {id:194,first_name:"Sébastien".to_string(),last_name:"Lemire".to_string()},
        SpeakerResponse {id:195,first_name:"Branden".to_string(),last_name:"Leslie".to_string()},
        SpeakerResponse {id:196,first_name:"Chris".to_string(),last_name:"Lewis".to_string()},
        SpeakerResponse {id:197,first_name:"Leslyn".to_string(),last_name:"Lewis".to_string()},
        SpeakerResponse {id:198,first_name:"Ron".to_string(),last_name:"Liepert".to_string()},
        SpeakerResponse {id:199,first_name:"Joël".to_string(),last_name:"Lightbound".to_string()},
        SpeakerResponse {id:200,first_name:"Dane".to_string(),last_name:"Lloyd".to_string()},
        SpeakerResponse {id:201,first_name:"Ben".to_string(),last_name:"Lobb".to_string()},
        SpeakerResponse {id:202,first_name:"Wayne".to_string(),last_name:"Long".to_string()},
        SpeakerResponse {id:203,first_name:"Lloyd".to_string(),last_name:"Longfield".to_string()},
        SpeakerResponse {id:204,first_name:"Tim".to_string(),last_name:"Louis".to_string()},
        SpeakerResponse {id:205,first_name:"Lawrence".to_string(),last_name:"MacAulay".to_string()},
        SpeakerResponse {id:206,first_name:"Heath".to_string(),last_name:"MacDonald".to_string()},
        SpeakerResponse {id:207,first_name:"Alistair".to_string(),last_name:"MacGregor".to_string()},
        SpeakerResponse {id:208,first_name:"Dave".to_string(),last_name:"MacKenzie".to_string()},
        SpeakerResponse {id:209,first_name:"Steven".to_string(),last_name:"MacKinnon".to_string()},
        SpeakerResponse {id:210,first_name:"Larry".to_string(),last_name:"Maguire".to_string()},
        SpeakerResponse {id:211,first_name:"Shuvaloy".to_string(),last_name:"Majumdar".to_string()},
        SpeakerResponse {id:212,first_name:"James".to_string(),last_name:"Maloney".to_string()},
        SpeakerResponse {id:213,first_name:"Richard".to_string(),last_name:"Martel".to_string()},
        SpeakerResponse {id:214,first_name:"Soraya".to_string(),last_name:"Martinez Ferrada".to_string()},
        SpeakerResponse {id:215,first_name:"Brian".to_string(),last_name:"Masse".to_string()},
        SpeakerResponse {id:216,first_name:"Lindsay".to_string(),last_name:"Mathyssen".to_string()},
        SpeakerResponse {id:217,first_name:"Bryan".to_string(),last_name:"May".to_string()},
        SpeakerResponse {id:218,first_name:"Elizabeth".to_string(),last_name:"May".to_string()},
        SpeakerResponse {id:219,first_name:"Dan".to_string(),last_name:"Mazier".to_string()},
        SpeakerResponse {id:220,first_name:"Kelly".to_string(),last_name:"McCauley".to_string()},
        SpeakerResponse {id:221,first_name:"Ken".to_string(),last_name:"McDonald".to_string()},
        SpeakerResponse {id:222,first_name:"David".to_string(),last_name:"McGuinty".to_string()},
        SpeakerResponse {id:223,first_name:"John".to_string(),last_name:"McKay".to_string()},
        SpeakerResponse {id:224,first_name:"Ron".to_string(),last_name:"McKinnon".to_string()},
        SpeakerResponse {id:225,first_name:"Greg".to_string(),last_name:"McLean".to_string()},
        SpeakerResponse {id:226,first_name:"Michael".to_string(),last_name:"McLeod".to_string()},
        SpeakerResponse {id:227,first_name:"Heather".to_string(),last_name:"McPherson".to_string()},
        SpeakerResponse {id:228,first_name:"Eric".to_string(),last_name:"Melillo".to_string()},
        SpeakerResponse {id:229,first_name:"Alexandra".to_string(),last_name:"Mendès".to_string()},
        SpeakerResponse {id:230,first_name:"Marco".to_string(),last_name:"Mendicino".to_string()},
        SpeakerResponse {id:231,first_name:"Wilson".to_string(),last_name:"Miao".to_string()},
        SpeakerResponse {id:232,first_name:"Kristina".to_string(),last_name:"Michaud".to_string()},
        SpeakerResponse {id:233,first_name:"Marc".to_string(),last_name:"Miller".to_string()},
        SpeakerResponse {id:234,first_name:"Rob".to_string(),last_name:"Moore".to_string()},
        SpeakerResponse {id:235,first_name:"Marty".to_string(),last_name:"Morantz".to_string()},
        SpeakerResponse {id:236,first_name:"Mike".to_string(),last_name:"Morrice".to_string()},
        SpeakerResponse {id:237,first_name:"Rob".to_string(),last_name:"Morrison".to_string()},
        SpeakerResponse {id:238,first_name:"Bobby".to_string(),last_name:"Morrissey".to_string()},
        SpeakerResponse {id:239,first_name:"Glen".to_string(),last_name:"Motz".to_string()},
        SpeakerResponse {id:240,first_name:"Joyce".to_string(),last_name:"Murray".to_string()},
        SpeakerResponse {id:241,first_name:"Dan".to_string(),last_name:"Muys".to_string()},
        SpeakerResponse {id:242,first_name:"Yasir".to_string(),last_name:"Naqvi".to_string()},
        SpeakerResponse {id:243,first_name:"John".to_string(),last_name:"Nater".to_string()},
        SpeakerResponse {id:244,first_name:"Mary".to_string(),last_name:"Ng".to_string()},
        SpeakerResponse {id:245,first_name:"Taleeb".to_string(),last_name:"Noormohamed".to_string()},
        SpeakerResponse {id:246,first_name:"Christine".to_string(),last_name:"Normandin".to_string()},
        SpeakerResponse {id:247,first_name:"Jennifer".to_string(),last_name:"O'Connell".to_string()},
        SpeakerResponse {id:248,first_name:"Seamus".to_string(),last_name:"O'Regan".to_string()},
        SpeakerResponse {id:249,first_name:"Erin".to_string(),last_name:"O'Toole".to_string()},
        SpeakerResponse {id:250,first_name:"Rob".to_string(),last_name:"Oliphant".to_string()},
        SpeakerResponse {id:251,first_name:"Jeremy".to_string(),last_name:"Patzer".to_string()},
        SpeakerResponse {id:252,first_name:"Pierre".to_string(),last_name:"Paul-Hus".to_string()},
        SpeakerResponse {id:253,first_name:"Monique".to_string(),last_name:"Pauzé".to_string()},
        SpeakerResponse {id:254,first_name:"Rick".to_string(),last_name:"Perkins".to_string()},
        SpeakerResponse {id:255,first_name:"Yves".to_string(),last_name:"Perron".to_string()},
        SpeakerResponse {id:256,first_name:"Ginette".to_string(),last_name:"Petitpas Taylor".to_string()},
        SpeakerResponse {id:257,first_name:"Louis".to_string(),last_name:"Plamondon".to_string()},
        SpeakerResponse {id:258,first_name:"Pierre".to_string(),last_name:"Poilievre".to_string()},
        SpeakerResponse {id:259,first_name:"Marcus".to_string(),last_name:"Powlowski".to_string()},
        SpeakerResponse {id:260,first_name:"Carla".to_string(),last_name:"Qualtrough".to_string()},
        SpeakerResponse {id:261,first_name:"Alain".to_string(),last_name:"Rayes".to_string()},
        SpeakerResponse {id:262,first_name:"Brad".to_string(),last_name:"Redekopp".to_string()},
        SpeakerResponse {id:263,first_name:"Scott".to_string(),last_name:"Reid".to_string()},
        SpeakerResponse {id:264,first_name:"Michelle".to_string(),last_name:"Rempel Garner".to_string()},
        SpeakerResponse {id:265,first_name:"Blake".to_string(),last_name:"Richards".to_string()},
        SpeakerResponse {id:266,first_name:"Anna".to_string(),last_name:"Roberts".to_string()},
        SpeakerResponse {id:267,first_name:"Yves".to_string(),last_name:"Robillard".to_string()},
        SpeakerResponse {id:268,first_name:"Pablo".to_string(),last_name:"Rodríguez".to_string()},
        SpeakerResponse {id:269,first_name:"Churence".to_string(),last_name:"Rogers".to_string()},
        SpeakerResponse {id:270,first_name:"Sherry".to_string(),last_name:"Romanado".to_string()},
        SpeakerResponse {id:271,first_name:"Lianne".to_string(),last_name:"Rood".to_string()},
        SpeakerResponse {id:272,first_name:"Anthony".to_string(),last_name:"Rota".to_string()},
        SpeakerResponse {id:273,first_name:"Alex".to_string(),last_name:"Ruff".to_string()},
        SpeakerResponse {id:274,first_name:"Ruby".to_string(),last_name:"Sahota".to_string()},
        SpeakerResponse {id:275,first_name:"Harjit".to_string(),last_name:"Sajjan".to_string()},
        SpeakerResponse {id:276,first_name:"Ya'ara".to_string(),last_name:"Saks".to_string()},
        SpeakerResponse {id:277,first_name:"Darrell".to_string(),last_name:"Samson".to_string()},
        SpeakerResponse {id:278,first_name:"Randeep".to_string(),last_name:"Sarai".to_string()},
        SpeakerResponse {id:279,first_name:"Louis-Philippe".to_string(),last_name:"Sauvé".to_string()},
        SpeakerResponse {id:280,first_name:"Simon-Pierre".to_string(),last_name:"Savard-Tremblay".to_string()},
        SpeakerResponse {id:281,first_name:"Francis".to_string(),last_name:"Scarpaleggia".to_string()},
        SpeakerResponse {id:282,first_name:"Andrew".to_string(),last_name:"Scheer".to_string()},
        SpeakerResponse {id:283,first_name:"Peter".to_string(),last_name:"Schiefke".to_string()},
        SpeakerResponse {id:284,first_name:"Jamie".to_string(),last_name:"Schmale".to_string()},
        SpeakerResponse {id:285,first_name:"Kyle".to_string(),last_name:"Seeback".to_string()},
        SpeakerResponse {id:286,first_name:"Marc".to_string(),last_name:"Serré".to_string()},
        SpeakerResponse {id:287,first_name:"Judy".to_string(),last_name:"Sgro".to_string()},
        SpeakerResponse {id:288,first_name:"Brenda".to_string(),last_name:"Shanahan".to_string()},
        SpeakerResponse {id:289,first_name:"Terry".to_string(),last_name:"Sheehan".to_string()},
        SpeakerResponse {id:290,first_name:"Martin".to_string(),last_name:"Shields".to_string()},
        SpeakerResponse {id:291,first_name:"Doug".to_string(),last_name:"Shipley".to_string()},
        SpeakerResponse {id:292,first_name:"Maninder".to_string(),last_name:"Sidhu".to_string()},
        SpeakerResponse {id:293,first_name:"Sonia".to_string(),last_name:"Sidhu".to_string()},
        SpeakerResponse {id:294,first_name:"Mario".to_string(),last_name:"Simard".to_string()},
        SpeakerResponse {id:295,first_name:"Nathalie".to_string(),last_name:"Sinclair-Desgagné".to_string()},
        SpeakerResponse {id:296,first_name:"Jagmeet".to_string(),last_name:"Singh".to_string()},
        SpeakerResponse {id:297,first_name:"Clifford".to_string(),last_name:"Small".to_string()},
        SpeakerResponse {id:298,first_name:"Francesco".to_string(),last_name:"Sorbara".to_string()},
        SpeakerResponse {id:299,first_name:"Gerald".to_string(),last_name:"Soroka".to_string()},
        SpeakerResponse {id:300,first_name:"Charles".to_string(),last_name:"Sousa".to_string()},
        SpeakerResponse {id:301,first_name:"Sven".to_string(),last_name:"Spengemann".to_string()},
        SpeakerResponse {id:302,first_name:"Pascale".to_string(),last_name:"St-Onge".to_string()},
        SpeakerResponse {id:303,first_name:"Gabriel".to_string(),last_name:"Ste-Marie".to_string()},
        SpeakerResponse {id:304,first_name:"Warren".to_string(),last_name:"Steinley".to_string()},
        SpeakerResponse {id:305,first_name:"Don".to_string(),last_name:"Stewart".to_string()},
        SpeakerResponse {id:306,first_name:"Jake".to_string(),last_name:"Stewart".to_string()},
        SpeakerResponse {id:307,first_name:"Mark".to_string(),last_name:"Strahl".to_string()},
        SpeakerResponse {id:308,first_name:"Shannon".to_string(),last_name:"Stubbs".to_string()},
        SpeakerResponse {id:309,first_name:"Jenna".to_string(),last_name:"Sudds".to_string()},
        SpeakerResponse {id:310,first_name:"Filomena".to_string(),last_name:"Tassi".to_string()},
        SpeakerResponse {id:311,first_name:"Leah".to_string(),last_name:"Taylor Roy".to_string()},
        SpeakerResponse {id:312,first_name:"Luc".to_string(),last_name:"Thériault".to_string()},
        SpeakerResponse {id:313,first_name:"Alain".to_string(),last_name:"Therrien".to_string()},
        SpeakerResponse {id:314,first_name:"Rachael".to_string(),last_name:"Thomas".to_string()},
        SpeakerResponse {id:315,first_name:"Joanne".to_string(),last_name:"Thompson".to_string()},
        SpeakerResponse {id:316,first_name:"Corey".to_string(),last_name:"Tochor".to_string()},
        SpeakerResponse {id:317,first_name:"Fraser".to_string(),last_name:"Tolmie".to_string()},
        SpeakerResponse {id:318,first_name:"Justin".to_string(),last_name:"Trudeau".to_string()},
        SpeakerResponse {id:319,first_name:"Denis".to_string(),last_name:"Trudel".to_string()},
        SpeakerResponse {id:320,first_name:"Ryan".to_string(),last_name:"Turnbull".to_string()},
        SpeakerResponse {id:321,first_name:"Tim".to_string(),last_name:"Uppal".to_string()},
        SpeakerResponse {id:322,first_name:"Rechie".to_string(),last_name:"Valdez".to_string()},
        SpeakerResponse {id:323,first_name:"Tony".to_string(),last_name:"Van Bynen".to_string()},
        SpeakerResponse {id:324,first_name:"Adam".to_string(),last_name:"Van Koeverden".to_string()},
        SpeakerResponse {id:325,first_name:"Tako".to_string(),last_name:"Van Popta".to_string()},
        SpeakerResponse {id:326,first_name:"Dan".to_string(),last_name:"Vandal".to_string()},
        SpeakerResponse {id:327,first_name:"Anita".to_string(),last_name:"Vandenbeld".to_string()},
        SpeakerResponse {id:328,first_name:"Karen".to_string(),last_name:"Vecchio".to_string()},
        SpeakerResponse {id:329,first_name:"Gary".to_string(),last_name:"Vidal".to_string()},
        SpeakerResponse {id:330,first_name:"Dominique".to_string(),last_name:"Vien".to_string()},
        SpeakerResponse {id:331,first_name:"Arnold".to_string(),last_name:"Viersen".to_string()},
        SpeakerResponse {id:332,first_name:"Julie".to_string(),last_name:"Vignola".to_string()},
        SpeakerResponse {id:333,first_name:"René".to_string(),last_name:"Villemure".to_string()},
        SpeakerResponse {id:334,first_name:"Arif".to_string(),last_name:"Virani".to_string()},
        SpeakerResponse {id:335,first_name:"Brad".to_string(),last_name:"Vis".to_string()},
        SpeakerResponse {id:336,first_name:"Kevin".to_string(),last_name:"Vuong".to_string()},
        SpeakerResponse {id:337,first_name:"Cathay".to_string(),last_name:"Wagantall".to_string()},
        SpeakerResponse {id:338,first_name:"Chris".to_string(),last_name:"Warkentin".to_string()},
        SpeakerResponse {id:339,first_name:"Kevin".to_string(),last_name:"Waugh".to_string()},
        SpeakerResponse {id:340,first_name:"Len".to_string(),last_name:"Webber".to_string()},
        SpeakerResponse {id:341,first_name:"Patrick".to_string(),last_name:"Weiler".to_string()},
        SpeakerResponse {id:342,first_name:"Jonathan".to_string(),last_name:"Wilkinson".to_string()},
        SpeakerResponse {id:343,first_name:"Ryan".to_string(),last_name:"Williams".to_string()},
        SpeakerResponse {id:344,first_name:"John".to_string(),last_name:"Williamson".to_string()},
        SpeakerResponse {id:345,first_name:"Jean".to_string(),last_name:"Yip".to_string()},
        SpeakerResponse {id:346,first_name:"Salma".to_string(),last_name:"Zahid".to_string()},
        SpeakerResponse {id:347,first_name:"Bonita".to_string(),last_name:"Zarrillo".to_string()},
        SpeakerResponse {id:348,first_name:"Bob".to_string(),last_name:"Zimmer".to_string()},
        SpeakerResponse {id:349,first_name:"Sameer".to_string(),last_name:"Zuberi".to_string()},
        SpeakerResponse {id:350,first_name:"Charles".to_string(),last_name:"Robert".to_string()},
        SpeakerResponse {id:351,first_name:"Volodymyr".to_string(),last_name:"Zelenskyy".to_string()},
        SpeakerResponse {id:352,first_name:"George".to_string(),last_name:"Furey".to_string()},
        SpeakerResponse {id:353,first_name:"Ursula".to_string(),last_name:"von der Leyen".to_string()},
        SpeakerResponse {id:354,first_name:"Joseph".to_string(),last_name:"Biden".to_string()},
        SpeakerResponse {id:355,first_name:"Raymonde".to_string(),last_name:"Gagné".to_string()},
        SpeakerResponse {id:356,first_name:"Kristian".to_string(),last_name:"Firth".to_string()}
    ]
}

pub fn get_breakdown_word_count(_connection: &mut MysqlConnection, breakdown_type: BreakdownType, _word: &str) -> Vec<BreakdownResponse> {
    match breakdown_type {
        BreakdownType::Party => vec![
            BreakdownResponse {id:1,name:"Liberal".to_string(),colour:"EA6D6A".to_string(),count:175,score:2.192533},
            BreakdownResponse {id:2,name:"Conservative".to_string(),colour:"6495ED".to_string(),count:631,score:6.753006},
            BreakdownResponse {id:3,name:"Bloc".to_string(),colour:"87CEFA".to_string(),count:222,score:6.9208617},
            BreakdownResponse {id:4,name:"NDP".to_string(),colour:"F4A460".to_string(),count:274,score:8.032308},
            BreakdownResponse {id:5,name:"Green".to_string(),colour:"98CA66".to_string(),count:207,score:48.23286},
            BreakdownResponse {id:6,name:"Independent".to_string(),colour:"DCDCDC".to_string(),count:3,score:2.5524747}
        ],
        BreakdownType::Gender => vec![
            BreakdownResponse {id:1,name:"female".to_string(),colour:"F4F462".to_string(),count:1900,score:28.98253},
            BreakdownResponse {id:2,name:"male".to_string(),colour:"ABF462".to_string(),count:3468,score:19.467318},
            BreakdownResponse {id:3,name:"two-spirit".to_string(),colour:"AB62F4".to_string(),count:22,score:16.175756}
        ],
        BreakdownType::Province => vec![
            BreakdownResponse {id:1,name:"Alberta".to_string(),colour:"6495ED".to_string(),count:54,score:1.7877634},
            BreakdownResponse {id:2,name:"British Columbia".to_string(),colour:"F4A460".to_string(),count:100,score:2.822971},
            BreakdownResponse {id:3,name:"Manitoba".to_string(),colour:"98CA66".to_string(),count:98,score:4.46076},
            BreakdownResponse {id:4,name:"New Brunswick".to_string(),colour:"E996E9".to_string(),count:10,score:2.9614272},
            BreakdownResponse {id:7,name:"Nova Scotia".to_string(),colour:"BF96E9".to_string(),count:16,score:1.8575255},
            BreakdownResponse {id:8,name:"Nunavut".to_string(),colour:"96ABE9".to_string(),count:2,score:1.7631865},
            BreakdownResponse {id:9,name:"Ontario".to_string(),colour:"EA6D6A".to_string(),count:266,score:3.496633},
            BreakdownResponse {id:11,name:"Quebec".to_string(),colour:"87CEFA".to_string(),count:155,score:2.714894},
            BreakdownResponse {id:12,name:"Saskatchewan".to_string(),colour:"FFF169".to_string(),count:11,score:1.2284546},
        ],
        BreakdownType::Speaker => vec![
            BreakdownResponse {id:242,name:"Yasir Naqvi".to_string(),colour:"EA6D6A".to_string(),count:53,score:95.425},
            BreakdownResponse {id:164,name:"Peter Julian".to_string(),colour:"F4A460".to_string(),count:258,score:82.8277},
            BreakdownResponse {id:79,name:"Leila Dance".to_string(),colour:"F4A460".to_string(),count:2,score:67.40816},
            BreakdownResponse {id:171,name:"Robert Kitchen".to_string(),colour:"6495ED".to_string(),count:22,score:63.096912},
            BreakdownResponse {id:315,name:"Joanne Thompson".to_string(),colour:"EA6D6A".to_string(),count:10,score:62.75494},
            BreakdownResponse {id:259,name:"Marcus Powlowski".to_string(),colour:"EA6D6A".to_string(),count:12,score:57.034218},
            BreakdownResponse {id:82,name:"Don Davies".to_string(),colour:"F4A460".to_string(),count:55,score:46.690887},
            BreakdownResponse {id:146,name:"Lisa Hepfner".to_string(),colour:"EA6D6A".to_string(),count:15,score:44.9991},
            BreakdownResponse {id:46,name:"Alexandre Boulerice".to_string(),colour:"F4A460".to_string(),count:71,score:44.773483},
            BreakdownResponse {id:293,name:"Sonia Sidhu".to_string(),colour:"EA6D6A".to_string(),count:9,score:41.430744},
        ],
    }
}

pub fn get_population_word_count(_connection: &mut MysqlConnection, _word: &str) -> Vec<PopulationResponse> {
    vec![
        PopulationResponse {id:1,name:"Edmonton Manning".to_string(),population:132224,area:157.08,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:2,name:"Parry Sound-Muskoka".to_string(),population:104494,area:12237.99,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:3,name:"Central Okanagan—Similkameen—Nicola".to_string(),population:122340,area:15965.94,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:4,name:"Cloverdale—Langley City".to_string(),population:130665,area:59.42,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:5,name:"Mississauga Centre".to_string(),population:127377,area:23.11,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:6,name:"Brampton Centre".to_string(),population:104557,area:43.62,colour:"EA6D6A".to_string(),count:8,score:93.512566},
        PopulationResponse {id:7,name:"Niagara West".to_string(),population:96946,area:988.1,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:8,name:"Oakville".to_string(),population:122322,area:78.35,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:9,name:"Scarborough—Rouge Park".to_string(),population:102254,area:53.23,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:10,name:"Timmins-James Bay".to_string(),population:80785,area:241782.68,colour:"F4A460".to_string(),count:22,score:12.217945},
        PopulationResponse {id:11,name:"North Okanagan—Shuswap".to_string(),population:136520,area:16158.36,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:12,name:"Madawaska—Restigouche".to_string(),population:60184,area:11681.73,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:13,name:"Nepean".to_string(),population:132769,area:171.54,colour:"EA6D6A".to_string(),count:11,score:13.038428},
        PopulationResponse {id:14,name:"Churchill—Keewatinook Aski".to_string(),population:81258,area:420975.01,colour:"F4A460".to_string(),count:8,score:9.924204},
        PopulationResponse {id:15,name:"Fredericton".to_string(),population:87436,area:1499.26,colour:"EA6D6A".to_string(),count:1,score:1.7755681},
        PopulationResponse {id:16,name:"Skeena—Bulkley Valley".to_string(),population:89689,area:325624.67,colour:"F4A460".to_string(),count:0,score:0.0},
        PopulationResponse {id:17,name:"Niagara Centre".to_string(),population:119809,area:301.73,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:18,name:"Steveston—Richmond East".to_string(),population:102230,area:85.87,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:19,name:"Etobicoke Centre".to_string(),population:118483,area:37.05,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:20,name:"Niagara Falls".to_string(),population:146404,area:507.84,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:21,name:"Foothills".to_string(),population:115118,area:20751.67,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:22,name:"Leeds—Grenville—Thousand Islands and Rideau Lakes".to_string(),population:104070,area:3355.61,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:23,name:"Nanaimo—Ladysmith".to_string(),population:134509,area:1726.78,colour:"F4A460".to_string(),count:2,score:2.180193},
        PopulationResponse {id:24,name:"Pierre-Boucher—Les Patriotes—Verchères".to_string(),population:103020,area:685.16,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:25,name:"Sydney—Victoria".to_string(),population:72361,area:4282.09,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:26,name:"La Pointe-de-l'Île".to_string(),population:110486,area:41.44,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:27,name:"Burnaby North—Seymour".to_string(),population:108794,area:114.56,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:28,name:"Outremont".to_string(),population:103620,area:11.94,colour:"EA6D6A".to_string(),count:3,score:3.8357284},
        PopulationResponse {id:29,name:"Toronto—St. Paul's".to_string(),population:116953,area:13.12,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:31,name:"Portage—Lisgar".to_string(),population:100417,area:12559.18,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:32,name:"Montarville".to_string(),population:100515,area:150.28,colour:"87CEFA".to_string(),count:43,score:92.74437},
        PopulationResponse {id:33,name:"Mégantic—L'Érable".to_string(),population:88894,area:5930.4,colour:"6495ED".to_string(),count:2,score:1.1857332},
        PopulationResponse {id:34,name:"Abitibi—Baie-James—Nunavik—Eeyou".to_string(),population:89087,area:731401.36,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:35,name:"Selkirk—Interlake—Eastman".to_string(),population:101373,area:19210.88,colour:"6495ED".to_string(),count:4,score:3.4425778},
        PopulationResponse {id:36,name:"Compton—Stanstead".to_string(),population:111088,area:4554.83,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:37,name:"St. Catharines".to_string(),population:114782,area:55.14,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:38,name:"Elmwood—Transcona".to_string(),population:101691,area:49.53,colour:"F4A460".to_string(),count:0,score:0.0},
        PopulationResponse {id:39,name:"Scarborough Southwest".to_string(),population:111994,area:28.12,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:40,name:"Beloeil—Chambly".to_string(),population:125359,area:377.68,colour:"87CEFA".to_string(),count:22,score:27.173243},
        PopulationResponse {id:41,name:"Rimouski-Neigette—Témiscouata—Les Basques".to_string(),population:85556,area:7724.44,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:42,name:"North Island—Powell River".to_string(),population:111825,area:53540.47,colour:"F4A460".to_string(),count:3,score:2.396932},
        PopulationResponse {id:43,name:"Carlton Trail—Eagle Creek".to_string(),population:83395,area:28076.91,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:44,name:"Kings—Hants".to_string(),population:87744,area:4117.46,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:45,name:"Edmonton Centre".to_string(),population:109125,area:45.48,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:46,name:"Rosemont—La Petite-Patrie".to_string(),population:112909,area:10.71,colour:"F4A460".to_string(),count:28,score:17.657148},
        PopulationResponse {id:47,name:"Kitchener South—Hespeler".to_string(),population:119851,area:104.24,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:48,name:"Tobique—Mactaquac".to_string(),population:69344,area:14529.46,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:49,name:"Barrie—Innisfil".to_string(),population:120378,area:330.74,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:50,name:"Sherbrooke".to_string(),population:119038,area:99.31,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:51,name:"Brantford—Brant".to_string(),population:140139,area:829.18,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:52,name:"Lac-Saint-Jean".to_string(),population:103886,area:55366.57,colour:"87CEFA".to_string(),count:27,score:25.017605},
        PopulationResponse {id:53,name:"Red Deer—Lacombe".to_string(),population:131575,area:6199.55,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:54,name:"South Okanagan—West Kootenay".to_string(),population:123487,area:17688.91,colour:"F4A460".to_string(),count:2,score:1.81102},
        PopulationResponse {id:55,name:"Kamloops—Thompson—Cariboo".to_string(),population:135492,area:37623.21,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:56,name:"Winnipeg South Centre".to_string(),population:94803,area:44.64,colour:"EA6D6A".to_string(),count:2,score:8.263097},
        PopulationResponse {id:57,name:"Winnipeg South Centre".to_string(),population:94803,area:44.64,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:58,name:"Oshawa".to_string(),population:131067,area:60.67,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:59,name:"Charlottetown".to_string(),population:38809,area:44.27,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:60,name:"Thérèse-De Blainville".to_string(),population:106013,area:74.72,colour:"87CEFA".to_string(),count:1,score:1.2527561},
        PopulationResponse {id:61,name:"Waterloo".to_string(),population:127235,area:72.67,colour:"EA6D6A".to_string(),count:3,score:6.468584},
        PopulationResponse {id:62,name:"Calgary Skyview".to_string(),population:159642,area:121.47,colour:"EA6D6A".to_string(),count:4,score:17.117426},
        PopulationResponse {id:63,name:"Simcoe North".to_string(),population:120656,area:1752.09,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:64,name:"Saint-Maurice—Champlain".to_string(),population:111997,area:34186.99,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:65,name:"Drummond".to_string(),population:107967,area:1599.1,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:66,name:"Pontiac".to_string(),population:129781,area:26974.07,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:67,name:"Scarborough North".to_string(),population:94717,area:30.37,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:68,name:"Markham—Unionville".to_string(),population:128308,area:83.78,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:69,name:"Wellington—Halton Hills".to_string(),population:127873,area:1492.58,colour:"6495ED".to_string(),count:18,score:20.889668},
        PopulationResponse {id:70,name:"Hamilton East—Stoney Creek".to_string(),population:112028,area:67.27,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:71,name:"Victoria".to_string(),population:123482,area:40.26,colour:"F4A460".to_string(),count:6,score:5.9473066},
        PopulationResponse {id:72,name:"St. Albert—Edmonton".to_string(),population:130822,area:104.4,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:73,name:"Acadie—Bathurst".to_string(),population:77594,area:5052.81,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:74,name:"Don Valley East".to_string(),population:95039,area:22.78,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:75,name:"West Nova".to_string(),population:83571,area:8869.18,colour:"6495ED".to_string(),count:1,score:0.65330017},
        PopulationResponse {id:76,name:"Toronto—Danforth".to_string(),population:105472,area:20.39,colour:"EA6D6A".to_string(),count:13,score:19.53037},
        PopulationResponse {id:77,name:"Pitt Meadows—Maple Ridge".to_string(),population:110416,area:2042.72,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:78,name:"Oakville North—Burlington".to_string(),population:148936,area:87.23,colour:"EA6D6A".to_string(),count:38,score:51.03754},
        PopulationResponse {id:79,name:"Elmwood—Transcona".to_string(),population:101691,area:49.53,colour:"F4A460".to_string(),count:0,score:0.0},
        PopulationResponse {id:80,name:"Kildonan—St. Paul".to_string(),population:91480,area:169.71,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:81,name:"York—Simcoe".to_string(),population:124458,area:790.74,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:82,name:"Vancouver Kingsway".to_string(),population:108054,area:15.3,colour:"F4A460".to_string(),count:0,score:0.0},
        PopulationResponse {id:83,name:"Salaberry—Suroît".to_string(),population:119351,area:2140.09,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:84,name:"Louis-Saint-Laurent".to_string(),population:123123,area:138.01,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:85,name:"Beauport—Côte-de-Beaupré—Île d'Orléans—Charlevoix".to_string(),population:95736,area:11115.81,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:86,name:"Rivière-des-Mille-Îles".to_string(),population:105589,area:114.95,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:87,name:"Edmonton Griesbach".to_string(),population:111699,area:45.95,colour:"F4A460".to_string(),count:21,score:15.4404955},
        PopulationResponse {id:88,name:"Surrey—Newton".to_string(),population:122264,area:30.03,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:89,name:"Dorval—Lachine—LaSalle".to_string(),population:119395,area:49.7,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:90,name:"Halifax West".to_string(),population:111944,area:227.31,colour:"EA6D6A".to_string(),count:5,score:12.311631},
        PopulationResponse {id:91,name:"Cariboo—Prince George".to_string(),population:111226,area:82820.22,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:92,name:"Don Valley North".to_string(),population:113663,area:24.34,colour:"DCDCDC".to_string(),count:0,score:0.0},
        PopulationResponse {id:93,name:"Simcoe—Grey".to_string(),population:151784,area:1856.92,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:94,name:"Red Deer—Mountain View".to_string(),population:120739,area:7645.5,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:95,name:"Glengarry—Prescott—Russell".to_string(),population:116463,area:2909.26,colour:"EA6D6A".to_string(),count:3,score:6.7816534},
        PopulationResponse {id:96,name:"Bourassa".to_string(),population:105637,area:13.54,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:97,name:"Québec".to_string(),population:98772,area:34.49,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:98,name:"Winnipeg South".to_string(),population:113370,area:101.27,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:99,name:"Stormont—Dundas—South Glengarry".to_string(),population:104493,area:2665.45,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:100,name:"Etobicoke North".to_string(),population:116003,area:47.77,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:101,name:"Davenport".to_string(),population:105946,area:12.08,colour:"EA6D6A".to_string(),count:1,score:1.2925408},
        PopulationResponse {id:102,name:"Willowdale".to_string(),population:118218,area:19.75,colour:"EA6D6A".to_string(),count:11,score:65.04642},
        PopulationResponse {id:103,name:"Laval—Les Îles".to_string(),population:111784,area:46.09,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:104,name:"Cumberland—Colchester".to_string(),population:82014,area:7903.27,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:105,name:"Chatham-Kent—Leamington".to_string(),population:113654,area:2039.68,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:106,name:"Beaches—East York".to_string(),population:109359,area:16.74,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:107,name:"Battlefords—Lloydminster".to_string(),population:70918,area:29158.72,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:108,name:"Provencher".to_string(),population:109445,area:18030.62,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:109,name:"Abbotsford".to_string(),population:110331,area:175.19,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:110,name:"Hull—Aylmer".to_string(),population:110881,area:62.45,colour:"EA6D6A".to_string(),count:1,score:0.6140696},
        PopulationResponse {id:111,name:"Peterborough—Kawartha".to_string(),population:125478,area:2955.93,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:112,name:"Halifax".to_string(),population:107010,area:214.58,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:113,name:"South Surrey—White Rock".to_string(),population:119672,area:144.29,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:114,name:"Dartmouth—Cole Harbour".to_string(),population:96165,area:89.99,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:115,name:"Mississauga East—Cooksville".to_string(),population:116346,area:32.02,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:116,name:"Ottawa—Vanier".to_string(),population:118806,area:39.19,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:117,name:"Rivière-du-Nord".to_string(),population:122654,area:355.35,colour:"87CEFA".to_string(),count:4,score:5.037339},
        PopulationResponse {id:118,name:"London North Centre".to_string(),population:138255,area:58.86,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:119,name:"Central Nova".to_string(),population:73188,area:9280.95,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:120,name:"University—Rosedale".to_string(),population:106216,area:13.57,colour:"EA6D6A".to_string(),count:2,score:1.7614162},
        PopulationResponse {id:121,name:"Vancouver Centre".to_string(),population:126995,area:11.2,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:122,name:"Mississauga—Malton".to_string(),population:116908,area:97.11,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:123,name:"Notre-Dame-de-Grâce—Westmount".to_string(),population:105601,area:16.04,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:124,name:"Renfrew—Nipissing—Pembroke".to_string(),population:107420,area:11359.2,colour:"6495ED".to_string(),count:2,score:2.4912806},
        PopulationResponse {id:125,name:"Notre-Dame-de-Grâce—Westmount".to_string(),population:105601,area:16.04,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:126,name:"Mirabel".to_string(),population:132930,area:836.53,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:127,name:"Esquimalt—Saanich—Sooke".to_string(),population:128644,area:328.51,colour:"F4A460".to_string(),count:0,score:0.0},
        PopulationResponse {id:128,name:"Laurentides—Labelle".to_string(),population:123796,area:17587.83,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:129,name:"Winnipeg Centre".to_string(),population:87499,area:28.3,colour:"F4A460".to_string(),count:28,score:25.105577},
        PopulationResponse {id:130,name:"Montmagny—L'Islet—Kamouraska—Rivière-du-Loup".to_string(),population:96724,area:7310.1,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:131,name:"Sherwood Park—Fort Saskatchewan".to_string(),population:126313,area:1226.98,colour:"6495ED".to_string(),count:13,score:2.9650578},
        PopulationResponse {id:132,name:"Kingston and the Islands".to_string(),population:126106,area:358.43,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:133,name:"Manicouagan".to_string(),population:88525,area:234442.27,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:134,name:"Sarnia—Lambton".to_string(),population:107077,area:1475.85,colour:"6495ED".to_string(),count:1,score:0.9979044},
        PopulationResponse {id:135,name:"Portneuf—Jacques-Cartier".to_string(),population:123243,area:7157.43,colour:"6495ED".to_string(),count:1,score:2.1501677},
        PopulationResponse {id:136,name:"Fort McMurray—Cold Lake".to_string(),population:110163,area:142870.37,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:137,name:"Burlington".to_string(),population:125435,area:75.96,colour:"EA6D6A".to_string(),count:1,score:1.1690164},
        PopulationResponse {id:138,name:"Lévis—Lotbinière".to_string(),population:118608,area:2065.42,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:139,name:"Kelowna—Lake Country".to_string(),population:136290,area:1565.53,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:140,name:"Hamilton Centre".to_string(),population:106439,area:30.24,colour:"F4A460".to_string(),count:15,score:24.123125},
        PopulationResponse {id:141,name:"Laurier—Sainte-Marie".to_string(),population:116932,area:10.36,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:142,name:"Thunder Bay—Superior North".to_string(),population:83325,area:76105.89,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:143,name:"Calgary Forest Lawn".to_string(),population:107939,area:52.74,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:144,name:"Yukon".to_string(),population:40232,area:472345.44,colour:"EA6D6A".to_string(),count:4,score:9.81836},
        PopulationResponse {id:145,name:"Fleetwood—Port Kells".to_string(),population:124987,area:69.52,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:146,name:"Hamilton Mountain".to_string(),population:107629,area:33.14,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:147,name:"Prince Albert".to_string(),population:80845,area:18765.59,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:148,name:"Ajax".to_string(),population:126666,area:66.64,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:149,name:"Mount Royal".to_string(),population:108494,area:22.63,colour:"EA6D6A".to_string(),count:11,score:33.90144},
        PopulationResponse {id:150,name:"Algoma—Manitoulin—Kapuskasing".to_string(),population:80310,area:92666.51,colour:"F4A460".to_string(),count:0,score:0.0},
        PopulationResponse {id:151,name:"York South—Weston".to_string(),population:116757,area:24.8,colour:"EA6D6A".to_string(),count:15,score:40.501133},
        PopulationResponse {id:152,name:"Long Range Mountains".to_string(),population:81716,area:37319.17,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:153,name:"Alfred-Pellan".to_string(),population:102020,area:113.41,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:154,name:"Nunavut".to_string(),population:36858,area:1836993.78,colour:"F4A460".to_string(),count:7,score:6.1711526},
        PopulationResponse {id:155,name:"Toronto Centre".to_string(),population:119901,area:5.84,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:156,name:"Markham—Stouffville".to_string(),population:135944,area:282.14,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:158,name:"Edmonton Riverbend".to_string(),population:124144,area:61.45,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:159,name:"Durham".to_string(),population:150235,area:868.87,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:160,name:"Courtenay—Alberni".to_string(),population:125116,area:7899.15,colour:"F4A460".to_string(),count:3,score:1.7842169},
        PopulationResponse {id:161,name:"Ahuntsic-Cartierville".to_string(),population:118170,area:21.68,colour:"EA6D6A".to_string(),count:41,score:153.42589},
        PopulationResponse {id:162,name:"Labrador".to_string(),population:26655,area:258539.4,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:163,name:"Richmond Hill".to_string(),population:114180,area:39.83,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:164,name:"New Westminster—Burnaby".to_string(),population:125253,area:26.29,colour:"F4A460".to_string(),count:3,score:0.9631128},
        PopulationResponse {id:165,name:"London West".to_string(),population:139305,area:77.32,colour:"EA6D6A".to_string(),count:2,score:5.9591203},
        PopulationResponse {id:166,name:"Cape Breton—Canso".to_string(),population:71380,area:8733.07,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:167,name:"Calgary Rocky Ridge".to_string(),population:145326,area:91.34,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:168,name:"Mississauga—Erin Mills".to_string(),population:123371,area:33.85,colour:"EA6D6A".to_string(),count:3,score:6.5142336},
        PopulationResponse {id:169,name:"Oxford".to_string(),population:124790,area:2246.42,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:170,name:"Brampton West".to_string(),population:162353,area:57.95,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:171,name:"Souris—Moose Mountain".to_string(),population:70579,area:41456.55,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:172,name:"Calgary Shepard".to_string(),population:163447,area:178.25,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:173,name:"Vimy".to_string(),population:119926,area:34.08,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:174,name:"Regina—Wascana".to_string(),population:89087,area:61.9,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:175,name:"Hastings—Lennox and Addington".to_string(),population:100636,area:8233.99,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:176,name:"Battle River—Crowfoot".to_string(),population:107979,area:51079.84,colour:"6495ED".to_string(),count:1,score:0.48401305},
        PopulationResponse {id:177,name:"Calgary Midnapore".to_string(),population:129110,area:82.77,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:178,name:"Windsor—Tecumseh".to_string(),population:122798,area:163.02,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:179,name:"Vancouver East".to_string(),population:118675,area:21.66,colour:"F4A460".to_string(),count:23,score:16.865261},
        PopulationResponse {id:180,name:"Edmonton—Wetaskiwin".to_string(),population:209431,area:4832.59,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:181,name:"Orléans".to_string(),population:139309,area:205.82,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:182,name:"Saint-Laurent".to_string(),population:102104,area:42.83,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:183,name:"LaSalle—Émard—Verdun".to_string(),population:107564,area:18.89,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:184,name:"Winnipeg North".to_string(),population:101221,area:37.4,colour:"EA6D6A".to_string(),count:7,score:0.63734746},
        PopulationResponse {id:185,name:"Thornhill".to_string(),population:115292,area:62.66,colour:"6495ED".to_string(),count:8,score:5.2341633},
        PopulationResponse {id:186,name:"Sudbury".to_string(),population:95537,area:843.58,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:187,name:"Shefford".to_string(),population:115924,area:1369.28,colour:"87CEFA".to_string(),count:1,score:0.521809},
        PopulationResponse {id:188,name:"Saint-Léonard—Saint-Michel".to_string(),population:115553,area:20.21,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:189,name:"Argenteuil—La Petite-Nation".to_string(),population:102311,area:4890.26,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:190,name:"Northumberland—Peterborough South".to_string(),population:118756,area:2728.47,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:191,name:"Beauséjour".to_string(),population:88797,area:3991.6,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:192,name:"Gaspésie—Les Îles-de-la-Madeleine".to_string(),population:75927,area:16783.86,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:193,name:"Beauce".to_string(),population:111034,area:4100.97,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:194,name:"Abitibi—Témiscamingue".to_string(),population:103735,area:33230.9,colour:"87CEFA".to_string(),count:1,score:0.62130326},
        PopulationResponse {id:195,name:"Portage—Lisgar".to_string(),population:100417,area:12559.18,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:196,name:"Essex".to_string(),population:134656,area:1096.69,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:197,name:"Haldimand—Norfolk".to_string(),population:116706,area:2848.14,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:198,name:"Calgary Signal Hill".to_string(),population:122818,area:65.83,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:199,name:"Louis-Hébert".to_string(),population:111322,area:94.4,colour:"EA6D6A".to_string(),count:3,score:30.248034},
        PopulationResponse {id:200,name:"Sturgeon River—Parkland".to_string(),population:124849,area:3976.8,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:201,name:"Huron—Bruce".to_string(),population:112929,area:5598.5,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:202,name:"Saint John—Rothesay".to_string(),population:81996,area:390.37,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:203,name:"Guelph".to_string(),population:143740,area:87.43,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:204,name:"Kitchener—Conestoga".to_string(),population:107134,area:896.18,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:205,name:"Cardigan".to_string(),population:39866,area:2547.64,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:206,name:"Malpeque".to_string(),population:39731,area:1606.4,colour:"EA6D6A".to_string(),count:1,score:10.743446},
        PopulationResponse {id:207,name:"Cowichan—Malahat—Langford".to_string(),population:124247,area:4553.56,colour:"F4A460".to_string(),count:0,score:0.0},
        PopulationResponse {id:208,name:"Oxford".to_string(),population:124790,area:2246.42,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:209,name:"Gatineau".to_string(),population:107286,area:118.79,colour:"EA6D6A".to_string(),count:1,score:1.8418242},
        PopulationResponse {id:210,name:"Brandon—Souris".to_string(),population:89812,area:17968.6,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:211,name:"Calgary Heritage".to_string(),population:109141,area:66.76,colour:"6495ED".to_string(),count:5,score:26.078339},
        PopulationResponse {id:212,name:"Etobicoke—Lakeshore".to_string(),population:141751,area:39.65,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:213,name:"Chicoutimi—Le Fjord".to_string(),population:80593,area:2534.54,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:214,name:"Hochelaga".to_string(),population:108264,area:19.57,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:215,name:"Windsor West".to_string(),population:130162,area:77.6,colour:"F4A460".to_string(),count:8,score:6.147226},
        PopulationResponse {id:216,name:"London—Fanshawe".to_string(),population:127068,area:114.85,colour:"F4A460".to_string(),count:32,score:36.486362},
        PopulationResponse {id:217,name:"Cambridge".to_string(),population:121301,area:347.93,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:218,name:"Saanich—Gulf Islands".to_string(),population:113541,area:498.88,colour:"98CA66".to_string(),count:10,score:3.3430169},
        PopulationResponse {id:219,name:"Dauphin—Swan River—Neepawa".to_string(),population:89503,area:50867.3,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:220,name:"Edmonton West".to_string(),population:134194,area:104.54,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:221,name:"Avalon".to_string(),population:87191,area:6357.25,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:222,name:"Ottawa South".to_string(),population:125090,area:73.01,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:223,name:"Scarborough-Guildwood".to_string(),population:104423,area:21.35,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:224,name:"Coquitlam—Port Coquitlam".to_string(),population:132004,area:597.3,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:225,name:"Calgary Centre".to_string(),population:130010,area:49.24,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:226,name:"Northwest Territories".to_string(),population:41070,area:1127711.92,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:227,name:"Edmonton Strathcona".to_string(),population:102188,area:81.66,colour:"F4A460".to_string(),count:128,score:67.433014},
        PopulationResponse {id:228,name:"Kenora".to_string(),population:64261,area:285752.27,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:229,name:"Brossard—Saint-Lambert".to_string(),population:114286,area:52.75,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:230,name:"Eglinton—Lawrence".to_string(),population:115832,area:22.65,colour:"EA6D6A".to_string(),count:4,score:4.6791835},
        PopulationResponse {id:231,name:"Richmond Centre".to_string(),population:107707,area:43.0,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:232,name:"Avignon—La Mitis—Matane—Matapédia".to_string(),population:70253,area:14433.2,colour:"87CEFA".to_string(),count:1,score:0.6335409},
        PopulationResponse {id:233,name:"Ville-Marie—Le Sud-Ouest—Île-des-Sœurs".to_string(),population:134555,area:22.19,colour:"EA6D6A".to_string(),count:6,score:15.204115},
        PopulationResponse {id:234,name:"Fundy Royal".to_string(),population:83721,area:7225.65,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:235,name:"Charleswood—St. James—Assiniboia—Headingley".to_string(),population:84767,area:204.85,colour:"6495ED".to_string(),count:9,score:12.621305},
        PopulationResponse {id:236,name:"Kitchener Centre".to_string(),population:113452,area:41.46,colour:"98CA66".to_string(),count:58,score:44.60269},
        PopulationResponse {id:237,name:"Kootenay—Columbia".to_string(),population:120759,area:63345.79,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:238,name:"Egmont".to_string(),population:35925,area:1482.86,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:239,name:"Medicine Hat—Cardston—Warner".to_string(),population:108391,area:29137.38,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:240,name:"Vancouver Quadra".to_string(),population:109328,area:40.29,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:241,name:"Flamborough—Glanbrook".to_string(),population:125692,area:886.65,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:242,name:"Ottawa Centre".to_string(),population:126360,area:32.43,colour:"EA6D6A".to_string(),count:3,score:5.4014153},
        PopulationResponse {id:243,name:"Perth Wellington".to_string(),population:113910,area:3580.35,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:244,name:"Markham—Thornhill".to_string(),population:97510,area:41.74,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:245,name:"Vancouver Granville".to_string(),population:109799,area:22.4,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:246,name:"Saint-Jean".to_string(),population:114617,area:686.27,colour:"87CEFA".to_string(),count:10,score:8.083225},
        PopulationResponse {id:247,name:"Pickering—Uxbridge".to_string(),population:120742,area:651.62,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:248,name:"St. John's South—Mount Pearl".to_string(),population:81544,area:422.71,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:249,name:"Durham".to_string(),population:150235,area:868.87,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:250,name:"Don Valley West".to_string(),population:101959,area:30.11,colour:"EA6D6A".to_string(),count:14,score:28.991508},
        PopulationResponse {id:251,name:"Cypress Hills—Grasslands".to_string(),population:68314,area:75611.48,colour:"6495ED".to_string(),count:1,score:0.80976903},
        PopulationResponse {id:252,name:"Charlesbourg—Haute-Saint-Charles".to_string(),population:109690,area:111.29,colour:"6495ED".to_string(),count:4,score:3.9870422},
        PopulationResponse {id:253,name:"Repentigny".to_string(),population:119204,area:198.59,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:254,name:"South Shore—St. Margarets".to_string(),population:94482,area:8461.63,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:255,name:"Berthier—Maskinongé".to_string(),population:105280,area:4114.68,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:256,name:"Moncton—Riverview—Dieppe".to_string(),population:101237,area:154.68,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:257,name:"Bécancour—Nicolet—Saurel".to_string(),population:96439,area:2743.24,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:258,name:"Carleton".to_string(),population:131375,area:1177.87,colour:"6495ED".to_string(),count:9,score:2.2852268},
        PopulationResponse {id:259,name:"Thunder Bay—Rainy River".to_string(),population:82357,area:32536.42,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:260,name:"Delta".to_string(),population:110721,area:186.77,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:261,name:"Richmond—Arthabaska".to_string(),population:110651,area:3427.45,colour:"DCDCDC".to_string(),count:0,score:0.0},
        PopulationResponse {id:262,name:"Saskatoon West".to_string(),population:87855,area:90.73,colour:"6495ED".to_string(),count:1,score:1.2697606},
        PopulationResponse {id:263,name:"Lanark—Frontenac—Kingston".to_string(),population:111424,area:6353.87,colour:"6495ED".to_string(),count:1,score:1.7288774},
        PopulationResponse {id:264,name:"Calgary Nose Hill".to_string(),population:115287,area:57.97,colour:"6495ED".to_string(),count:1,score:0.72623223},
        PopulationResponse {id:265,name:"Banff—Airdrie".to_string(),population:155580,area:12304.43,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:266,name:"King—Vaughan".to_string(),population:147695,area:424.52,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:267,name:"Marc-Aurèle-Fortin".to_string(),population:104636,area:52.55,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:268,name:"Honoré-Mercier".to_string(),population:104578,area:37.71,colour:"DCDCDC".to_string(),count:0,score:0.0},
        PopulationResponse {id:269,name:"Bonavista—Burin—Trinity".to_string(),population:71898,area:16529.46,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:270,name:"Longueuil—Charles-LeMoyne".to_string(),population:112257,area:37.44,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:271,name:"Lambton—Kent—Middlesex".to_string(),population:111242,area:4919.1,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:272,name:"Nipissing—Timiskaming".to_string(),population:89781,area:13115.67,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:273,name:"Bruce—Grey—Owen Sound".to_string(),population:113348,area:6089.27,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:274,name:"Brampton North".to_string(),population:125141,area:33.21,colour:"EA6D6A".to_string(),count:2,score:6.84697},
        PopulationResponse {id:275,name:"Vancouver South".to_string(),population:109339,area:20.69,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:276,name:"York Centre".to_string(),population:108307,area:35.12,colour:"EA6D6A".to_string(),count:7,score:11.155201},
        PopulationResponse {id:277,name:"Sackville—Preston—Chezzetcook".to_string(),population:89524,area:645.18,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:278,name:"Surrey Centre".to_string(),population:131670,area:40.34,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:279,name:"LaSalle—Émard—Verdun".to_string(),population:107564,area:18.89,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:280,name:"Saint-Hyacinthe—Bagot".to_string(),population:105086,area:1881.6,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:281,name:"Lac-Saint-Louis".to_string(),population:110093,area:78.21,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:282,name:"Regina—Qu'Appelle".to_string(),population:78140,area:12723.61,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:283,name:"Vaudreuil—Soulanges".to_string(),population:129612,area:392.62,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:284,name:"Haliburton—Kawartha Lakes—Brock".to_string(),population:122401,area:7772.15,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:285,name:"Dufferin—Caledon".to_string(),population:142838,area:2175.59,colour:"6495ED".to_string(),count:3,score:3.2175722},
        PopulationResponse {id:286,name:"Nickel Belt".to_string(),population:94947,area:26564.18,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:287,name:"Humber River—Black Creek".to_string(),population:111593,area:30.61,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:288,name:"Châteauguay—Lacolle".to_string(),population:105111,area:903.49,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:289,name:"Sault Ste. Marie".to_string(),population:79331,area:5540.4,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:290,name:"Bow River".to_string(),population:119458,area:23780.27,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:291,name:"Barrie—Springwater—Oro-Medonte".to_string(),population:106871,area:964.36,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:292,name:"Brampton East".to_string(),population:131677,area:84.48,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:293,name:"Brampton South".to_string(),population:132752,area:46.63,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:294,name:"Jonquière".to_string(),population:91073,area:37641.59,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:295,name:"Terrebonne".to_string(),population:119944,area:153.76,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:296,name:"Burnaby South".to_string(),population:120305,area:46.06,colour:"F4A460".to_string(),count:36,score:33.763187},
        PopulationResponse {id:297,name:"Coast of Bays—Central—Notre Dame".to_string(),population:74201,area:38674.01,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:298,name:"Vaughan—Woodbridge".to_string(),population:106810,area:79.59,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:299,name:"Yellowhead".to_string(),population:99218,area:77133.53,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:300,name:"Mississauga—Lakeshore".to_string(),population:117095,area:60.12,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:301,name:"Mississauga—Lakeshore".to_string(),population:117095,area:60.12,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:302,name:"Brome—Missisquoi".to_string(),population:113913,area:2779.12,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:303,name:"Joliette".to_string(),population:112418,area:8124.04,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:304,name:"Regina—Lewvan".to_string(),population:98492,area:58.01,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:305,name:"Toronto—St. Paul's".to_string(),population:116953,area:13.12,colour:"6495ED".to_string(),count:2,score:17.909914},
        PopulationResponse {id:306,name:"Miramichi—Grand Lake".to_string(),population:57520,area:16837.24,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:307,name:"Chilliwack—Hope".to_string(),population:112037,area:3283.75,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:308,name:"Lakeland".to_string(),population:105993,area:31028.15,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:309,name:"Kanata—Carleton".to_string(),population:116651,area:760.74,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:310,name:"Hamilton West—Ancaster—Dundas".to_string(),population:117565,area:101.02,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:311,name:"Aurora—Oak Ridges—Richmond Hill".to_string(),population:118883,area:94.47,colour:"EA6D6A".to_string(),count:3,score:5.6418552},
        PopulationResponse {id:312,name:"Montcalm".to_string(),population:118746,area:873.04,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:313,name:"La Prairie".to_string(),population:114968,area:277.52,colour:"87CEFA".to_string(),count:1,score:0.8508249},
        PopulationResponse {id:314,name:"Lethbridge".to_string(),population:123847,area:2958.96,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:315,name:"St. John's East".to_string(),population:87345,area:328.38,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:316,name:"Saskatoon—University".to_string(),population:88348,area:68.7,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:317,name:"Moose Jaw—Lake Centre—Lanigan".to_string(),population:80547,area:32079.29,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:318,name:"Papineau".to_string(),population:110813,area:9.9,colour:"EA6D6A".to_string(),count:30,score:9.448879},
        PopulationResponse {id:319,name:"Longueuil—Saint-Hubert".to_string(),population:115082,area:55.23,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:320,name:"Whitby".to_string(),population:138501,area:146.69,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:321,name:"Edmonton Mill Woods".to_string(),population:125992,area:51.22,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:322,name:"Mississauga—Streetsville".to_string(),population:116864,area:46.53,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:323,name:"Newmarket—Aurora".to_string(),population:127134,area:59.47,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:324,name:"Milton".to_string(),population:136993,area:447.36,colour:"EA6D6A".to_string(),count:13,score:5.936751},
        PopulationResponse {id:325,name:"Langley—Aldergrove".to_string(),population:133168,area:373.15,colour:"6495ED".to_string(),count:1,score:1.0778883},
        PopulationResponse {id:326,name:"Saint Boniface—Saint Vital".to_string(),population:95514,area:62.9,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:327,name:"Ottawa West—Nepean".to_string(),population:116409,area:66.0,colour:"EA6D6A".to_string(),count:22,score:86.271126},
        PopulationResponse {id:328,name:"Elgin—Middlesex—London".to_string(),population:126428,area:2482.02,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:329,name:"Desnethé—Missinippi—Churchill River".to_string(),population:71488,area:296772.09,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:330,name:"Bellechasse—Les Etchemins—Lévis".to_string(),population:120179,area:3201.11,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:331,name:"Peace River—Westlock".to_string(),population:107223,area:106395.3,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:332,name:"Beauport—Limoilou".to_string(),population:96064,area:33.35,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:333,name:"Trois-Rivières".to_string(),population:114064,area:125.31,colour:"87CEFA".to_string(),count:0,score:0.0},
        PopulationResponse {id:334,name:"Parkdale—High Park".to_string(),population:106750,area:14.83,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:335,name:"Mission—Matsqui—Fraser Canyon".to_string(),population:101216,area:21330.06,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:336,name:"Spadina—Fort York".to_string(),population:136213,area:12.76,colour:"DCDCDC".to_string(),count:6,score:9.688201},
        PopulationResponse {id:337,name:"Yorkton—Melville".to_string(),population:71220,area:41801.6,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:338,name:"Grande Prairie—Mackenzie".to_string(),population:119586,area:111864.57,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:339,name:"Saskatoon—Grasswood".to_string(),population:93277,area:335.23,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:340,name:"Calgary Confederation".to_string(),population:124064,area:54.24,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:341,name:"West Vancouver—Sunshine Coast—Sea to Sky Country".to_string(),population:131206,area:12990.95,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:342,name:"North Vancouver".to_string(),population:123025,area:335.08,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:343,name:"Bay of Quinte".to_string(),population:116016,area:1624.98,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:344,name:"New Brunswick Southwest".to_string(),population:67781,area:9885.7,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:345,name:"Scarborough—Agincourt".to_string(),population:103449,area:25.94,colour:"EA6D6A".to_string(),count:0,score:0.0},
        PopulationResponse {id:346,name:"Scarborough Centre".to_string(),population:113104,area:28.12,colour:"EA6D6A".to_string(),count:34,score:110.23571},
        PopulationResponse {id:347,name:"Port Moody—Coquitlam".to_string(),population:114853,area:95.16,colour:"F4A460".to_string(),count:0,score:0.0},
        PopulationResponse {id:348,name:"Prince George—Peace River—Northern Rockies".to_string(),population:108998,area:249105.22,colour:"6495ED".to_string(),count:0,score:0.0},
        PopulationResponse {id:349,name:"Pierrefonds—Dollard".to_string(),population:109497,area:50.74,colour:"EA6D6A".to_string(),count:5,score:20.920504}
    ]
}

pub fn get_speeches(_connection: &mut MysqlConnection, _breakdown_type: BreakdownType, _id: i32, _word: &str) -> Vec<SpeechResponse> {
    vec![ SpeechResponse {
        speaker: 218,
        text: "Mr. Speaker, I am honoured to present a petition regarding the Trans Mountain pipeline. It is of critical concern to the petitioners that the Trans Mountain pipeline expansion not take place. They point out that a diluted bitumen spill would devastate local ecosystems and economies throughout British Columbia, but particularly in the coastal zone and anywhere along the 800 water bodies, tributaries and rivers the pipeline would cross. The petitioners call on the government to cancel any plans to put public money into, or to approve any expansion of, the Trans Mountain pipeline.".to_string(),
        link: "https://www.ourcommons.ca/documentviewer/en/44-1/house/sitting-3/hansard".to_string(),
        start: PrimitiveDateTime::new(date!(2021-11-24), time!(15:30)),
        end: PrimitiveDateTime::new(date!(2021-11-24), time!(15:30)),
    }]
}
