[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
time = { version = "0.3.37", features = ["serde"] }
uuid = { version = "1.16.0", features = ["serde", "v4"] }
